### ISSUE TITLE
Postman Collection führt zu 404

### ISSUE THREAD

**Issue by mm-mereien** [Endereco/enderecoservice_api#10]
Die verlinkte Postman Collection führt zu einer 404 Seite:

https://www.endereco.de/wp-content/uploads/2021/11/Endereco-API.postman_collection.json_.zip

**Comment by iljamobilemojo** [comment]
Hallo Patrick,

danke für den Hinweis!

Wir haben den Link repariert.

Viele Grüße
Ilja
